### ISSUE TITLE
ilab should support multiple serving backends

### ISSUE THREAD

**Issue by cdoern** [instructlab/instructlab#1106]
ilab currently uses llama as the main backend to serve the models. llama doesn't have as much extensive GPU and multi GPU support. 

in developing some new tooling, custom vllm support needed to be quickly developed. ilab should natively be able to support vllm as a backend and other backends that exist. 

something like `--backend` when running `ilab serve` `chat` or `generate` would make sense since all of these commands have the ability to start a server.

This might need to be an enhancement. I am open to writing one if needed.

cc @jaideepr97

**Comment by nathan-weinberg** [comment]
@cdoern since this is specific to the CLI, IMHO no enhancement is nessessary

**Comment by alimaredia** [comment]
https://github.com/instructlab/instructlab/pull/1276 is an initial PR for how adding model serving with vllm would look. There is more work to be done there, but reviewers should have an idea for how the ideas below are implemented.

Since we're adding a new backend to serve, finalizing the UX for serving once for feature is where I want to start.

Here is my proposal of how I see the various `ilab model serve` commands looking:

**Bare-bones but model specific command**

```
ilab model serve --model-path <PATH> 
```

- Serves the model at <PATH>. 
- If the <PATH> is the path for a `.gguf` file then `llama-cpp` is automatically used as the model serving backend. 
- If the path is a directory, `vllm` is automatically used as the backend. 
- The path provided to `vllm` can either be to a Huggingface repo or a directory with `.safetensors`.

**Bare-bones command**

```
ilab model serve
```
- This command has the same behavior as the one above but the `--model-path` is whatever the default model path is in the config. This is the existing behavior of `ilab serve` today.

**Llama-cpp backend specific commands**

```
ilab model serve llama-cpp --model-path <PATH> --llama-cpp-gpu-layers 4 --llama-cpp-max-ctx-size 1024
```

- This command serves a model with `llama-cpp`. 
- The existing flags to `ilab serve` (besides `--model-path` & `--log-file`) are specific to the llama-cpp backend and are prefixed to indicate that. This is helpful so that there is no mix up of flags between backends.

**vllm backend specific commands**

```
ilab model serve vllm --model-path <PATH> --vllm-chat-template <PATH> --vllm-args "<MORE VLLM SPECIFIC ARGS>"
```

- This command serves a model with `vllm`. 
- If the path provided is not a directory, this command would error out.
- There are [dozens](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#command-line-arguments-for-the-server) of flags for vllm. I'm hoping to figure out the most popular ones and add them as flags to `ilab model serve vllm` with `--vllm-` as a prefix, similar to what was done with `llama-cpp` backend args above. 
- Any remaining flags can be specified in `--vllm-args`.

**Next steps**

Here are the TODOs I want to finalize and create sub-tasks or sub-issues for in this EPIC that I see as in scope for #1276 or the 6/13 Milestone:
- Get consensus on UX and command behavior (Original PR)
- Add support for custom vllms installed with custom venvs (I would like to see this as part of the original PR too but it could be split out)
- Add testing
    - How will our current e2e testing and github actions change?
- Docs for this feature
    - Where do they go?
- Figure out some of the most important vllm flags for users

Here are TODOs after the 6/13 Milestone:
- Serve vllm in background if there is no model being served when `ilab model chat` is invoked
- Support vllm inferencing on cpus[https://docs.vllm.ai/en/latest/getting_started/cpu-installation.html]
- Look into vllm not being able to serve merlinite model on the latest release when I checked earlier this week

@russellb @cdoern @n1hility What are your thoughts on the UX and the TODOs for the upcoming release?

**Comment by leseb** [comment]
A few points at first glance:

* I think for a better review this would benefit from a small design doc PR so we can put comments and discuss. Responding to this issue is going to be difficult.
* This feels unnatural: `ilab model serve llama-cpp`, I would imagine something like `ilab model serve --backend llama-cpp` instead. If additional backends or more complex configurations are added, the command structure might become less clear. Using `--backend` is immediately clear that --backend is an option, making the command more self-explanatory.
* checking on the `.gguf` extension seems "weak", I'd rather read the first byte of the image to determine if this is `.gguf` or not.
* When using a specific backend, I'd avoid repeating the backend name in the args like `--llama-cpp-gpu-layers`, which should simply be. `--gpu-layers`, we know the backend so no need to repeat it.
* For VLLM-supported flags, I think we should start with a subset we are comfortable with and progressively introduce more supported flags once we have good CI coverage. I wouldn't worry too much about the number of flags in general.

**Comment by alimaredia** [comment]
Per discussion in the community call yesterday, A pull request for a design doc has been opened: https://github.com/instructlab/dev-docs/pull/81

This doc covers the CLI UX and testing. Please move comments and feedback related to the design I proposed above to that PR.

**Comment by nathan-weinberg** [comment]
`ilab` as of `0.18.0` now supports multiple serving backends - `llama-cpp` was the original and we now also have support for `vLLM`
