### ISSUE TITLE
Low cpu usage on large core count systems

### ISSUE THREAD

**Issue by fontivan** [instructlab/instructlab#1146]
**Describe the bug**
I was testing `ilab generate` on a rather beefy node (though without any graphics card accelerators) and found that the cpu cores were somewhat underutilized. It almost looks like hyperthreading it not being used at all with how many cores are pegged at 100% and the rest are mostly at 0%.

**To Reproduce**
1. Run `ilab generate` in a taxonomy repo

**Expected behavior**
I would expect more uniform cpu usage such as nearly all the cores being used

**Screenshots**

**Device Info (please complete the following information):**
 - Hardware Specs: Dual socket Xeon Gold 6230R (104 threads), 376GB ram
 - OS Version: RHEL 9.3
 - Python Version: 3.9.18
 - InstructLab Version: 0.14.1

**Additional context**
![Screenshot from 2024-05-10 08-13-11](https://github.com/instructlab/instructlab/assets/21060660/5f8510f8-b3fd-47ae-807a-3079c14eeb65)

**Comment by fontivan** [comment]
I also see similar behaviour when using `ilab train` after the generation was completed
![image](https://github.com/instructlab/instructlab/assets/21060660/3182687d-d9be-4466-82bb-2a6846a78311)

**Comment by tiran** [comment]
The observed behavior is a feature that improves overall performance on traditional CPUs. Machine learning algorithms make heavy use of vector operations (SIMD/SSE/AVX) and matrix multiplication FMA (like fused-multiply-add). CPUs have only one vector engine per physical core. Hyper threading often causes performance issues because logical cores are contending for resources, cause cache evictions, and incur additional thread synchronization costs.

Traditional CPUs are not designed for ML workloads. You might be able to squeeze some more performance out of your system with [ipex](https://pytorch.org/tutorials/intermediate/torchserve_with_ipex.html) and by avoiding cross-socket memory access. Any decent GPU or hardware accelerator will be at least one magnitude faster.

**Comment by ivanbaldo** [comment]
Using the Hyperthreads / logical processors makes the process actually slower.
This should be documented on the README's and other places which mention those commands maybe, so that people don't waste time or report non-issues.

**Comment by ivanbaldo** [comment]
Strangely for me now with 0.16.1 `ilab train` uses only a single CPU core...

```bash
# ilab sysinfo
instructlab.version: 0.16.1
sys.version: 3.9.18 (main, Sep  7 2023, 00:00:00) 
[GCC 11.4.1 20230605 (Red Hat 11.4.1-2)]
sys.platform: linux
os.name: posix
platform.release: 6.8.0-35-generic
platform.machine: x86_64
torch.version: 2.3.1+cu121
torch.backends.cpu.capability: AVX2
torch.version.cuda: 12.1
torch.version.hip: None
torch.cuda.available: False
torch.backends.cuda.is_built: True
torch.backends.mps.is_built: False
torch.backends.mps.is_available: False
llama_cpp_python.version: 0.2.75
llama_cpp_python.supports_gpu_offload: False
```

**Comment by nathan-weinberg** [comment]
@fontivan could you try again with the latest `ilab` version?

**Comment by fontivan** [comment]
@nathan-weinberg generate with ilab 0.18.2 it looks significantly more evenly distributed, happy to consider this resolved.
![image](https://github.com/user-attachments/assets/c223f742-d036-46d5-8fe7-476ed4d1173d)
