### ISSUE TITLE
`ilab chat` 100% CPU not offloading to GPU

### ISSUE THREAD

**Issue by myrulezzz** [instructlab/instructlab#1403]
**Describe the bug**
I follow all the steps and downloading merlinite model. Then i run ilab serrve to serve the model
Going to another terminal and run ilab chat --model-family merlinite it stucks and the CPU is used 100%
Using A100 PCIE 80GB

**Expected behavior**
It should offload the model to GPU

**Device Info (please complete the following information):**
 - Hardware Specs: A100 PCIE 80GB
 - OS Version: Linux
 - Python Version: Python 3.10
 - InstructLab Version: lab, version 0.17.0

**Additional context**
Something is wrong with offloading model to GPU when serving. Tested on A100 on runpod

**Comment by tiran** [comment]
Please post the output of `ilab sysinfo`. You probably installed llama-cpp-python without CUDA support.

**Comment by andsty** [comment]
Because runpod has cuda preinstalled is it possible to install ilab without installing again cuda and use it with cuda?

**Comment by tiran** [comment]
You have build llama-cpp-python with CUDA support. This currently requires a build and development environment for CUDA with devel packages, compilers, and so on.

**Comment by andsty** [comment]
Ok ill check it out.Also quick question.can i train a model with both skills and knowledge at the same time and how do i define custom files?

**Comment by tiran** [comment]
Please use Slack for these types of question. You can find the invite link here: https://github.com/instructlab/community/blob/main/InstructLab_SLACK_GUIDE.md

**Comment by xsgordon** [comment]
I was having the same issue and on closer inspection of the pip output found that even having done "pip cache remove llama_cpp_python" it was still pulling it from cache somewhere. Using the following was more effective:

`$ pip install instructlab -C cmake.args="-DLLAMA_CUDA=on" **--no-cache-dir llama_cpp_python**`

**Comment by tiran** [comment]
> I was having the same issue and on closer inspection of the pip output found that even having done "pip cache remove llama_cpp_python" it was still pulling it from cache somewhere. Using the following was more effective:
> 
> `$ pip install instructlab -C cmake.args="-DLLAMA_CUDA=on" --no-cache-dir llama_cpp_python`

This will install the wrong version of llama_cpp_python. It pulls the latest version, we currently need a slightly older version.

Was pip pulling the wheel from the cache or the source dist? `pip cache remove llama_cpp_python` purges the locally built wheel from pip's cache, so `pip install` has to compile a new wheel. It's ok (and actually desired) to pull the sdist from pip's cache.

**Comment by xsgordon** [comment]
I think how I ended up down this path, and how other new users may as well, is something like this:

1. Ok this looks cool, let me try it out. Follow the instructions for getting it going quickly with no acceleration.
2. Ok this still looks cool, but is indeed slow. Follow the instructions for getting to going quickly with acceleration.

Without an additional step, just following the instructions wont work because if you went through (1) then you need to do (2) to force llama_cpp_python to get rebuilt with the relevant options.  From the perspective of a user who doesn't understand the pip that well this happens pretty transparently, you keep retrying the same steps and wondering why the resultant install isn't using the GPU.

The output is pretty verbose so the difference between:

`Requirement already satisfied: llama-cpp-python==0.2.75 in ./venv/lib64/python3.12/site-packages (from llama-cpp-python[server]==0.2.75->instructlab) (0.2.75)`

and

`Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... done
  Created wheel for llama-cpp-python: filename=llama_cpp_python-0.2.75-cp312-cp312-linux_x86_64.whl size=3684061 sha256=044bc504c2b52650fcb88ec68d466376fac4b6f88e963b6e0df2e441daa34446
  Stored in directory: /home/sgordon/.cache/pip/wheels/a6/11/d0/e0b4121ffe4bba55a1b3c2e0b9ad561d67a1ca6951900dcc62
Successfully built llama-cpp-python`

Buried among everything else going on isn't necessarily obvious. I do agree that the correct step someone should take in between these two is not what I proposed but actually `pip uninstall llama-python-cpp`, though in my case what I posted earlier did get me down a path where it was trying to build `llama_cpp_python` and giving me the specific feedback cues I needed on why my CUDA environment wasn't quite right yet.

**Comment by brian316** [comment]
the argument to install for cuda from the docs does nothing. it does not build the cuda version. 
```
pip install instructlab \
   -C cmake.args="-DLLAMA_CUDA=on" \
   -C cmake.args="-DLLAMA_NATIVE=off"
```

when i run the install directly as stated from [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) it builds and takes minutes to build unlike the command above.
```
CMAKE_ARGS="-DLLAMA_CUDA=on" pip install llama-cpp-python==0.2.79 --upgrade
```

it still doesnt work when i try to manually update that package though

**Comment by tiran** [comment]
I'm sorry that you are still having issues with llama-cpp. You are not the only one. I have created ticket https://github.com/instructlab/instructlab/issues/1517 for the problem. The ticket contains information how to recover from the situation.

**Comment by nathan-weinberg** [comment]
Closing in favor of #1517
