### ISSUE TITLE
log noise when running any command after training lib integration

### ISSUE THREAD

**Issue by russellb** [instructlab/instructlab#1465]
i'm getting this any time i run any command (post training merge)

```
[2024-06-25 20:02:11,013] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to mps (auto detect)
W0625 20:02:11.591000 8713899008 torch/distributed/elastic/multiprocessing/redirects.py:27] NOTE: Redirects are currently not supported in Windows or MacOs.
```

This also comes up when using `ilab` tab completion, so something like `ilab <tab>` also causes these messages to print. I assume that means this is happening at import time.

I also noticed that startup takes significantly longer than before - presumably because of what's now happening at import time that didn't before.

**Comment by russellb** [comment]
In the e2e CI job, I see a much longer blob emitted every time `ilab` is run:

```
[2024-06-26 18:32:02,395] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  NVIDIA Inference is only supported on Ampere and newer architectures
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.1), only 1.0.0 is known to be compatible
```

**Comment by russellb** [comment]
@JamesKunstle you mentioned on slack that you were looking at this. should it be assigned to you?

**Comment by tiran** [comment]
Most occurrences of the ugly log noise will go away with these PRs:

-  https://github.com/instructlab/instructlab/pull/1532
- https://github.com/instructlab/training/pull/116

For the remaining occurrences, it is going to be tricky to fix. The log messages are coming from DeepSpeed. The logging code in DeepSpeed goes really hard to circumvent common best practices around logging. It sets up its own logger with a hard-coded configuration and stream handler. 

https://github.com/microsoft/DeepSpeed/blob/aecfec7f510eb2a40f7afa50efe370f885e4d258/deepspeed/utils/logging.py#L20-L50

There is no easy way to monkey-patch the issue at runtime, because `import deepspeed` already emits log lines to stdout. Some like this might do the trick:

```
import contextlib
import os
import logging

with open(os.devnull, "w") as f:
    with contextlib.redirect_stdout(f):
        from deepspeed.utils.logging import logger as ds_logger

ds_logger.setLevel(logging.NOTSET)
ds_logger.propagate = True
for hdlr in ds_logger.handlers[:]:
    ds_logger.removeHandler(hdlr)
```

**Comment by mairin** [comment]
Can anyone test whether or not this is an issue still now that https://github.com/instructlab/instructlab/pull/1532
https://github.com/instructlab/training/pull/116 are merged?

**Comment by tiran** [comment]
I no longer see the log noise, but I have not checked all commands. It might still show up for `ilab model train`.

**Comment by nathan-weinberg** [comment]
Closing for now, we can reopen if it's still an issue
