### ISSUE TITLE
Python modules are not packaged until they are included in git

### ISSUE THREAD

**Issue by RobotSail** [instructlab/instructlab#1631]
Basically until a module is included in git, it won't be included in a package when we install via `pip install .`.
This is incredibly frustrating because all of our tests test using non-editable mode, and we require a thorough explanation of what every commit does. So how can something be tested when it can't be packaged?

**Comment by russellb** [comment]
> Basically until a module is included in git, it won't be included in a package when we install via `pip install .`. This is incredibly frustrating because all of our tests test using non-editable mode, and we require a thorough explanation of what every commit does. So how can something be tested when it can't be packaged?

Do you have a simple reproducer of the problem you're seeing?

**Comment by RobotSail** [comment]
@russellb Not published but you can reproduce this locally by doing:

1. Add a new module to an existing submodule - let's say `src/instructlab/model/mytest.py`
2. Throw in a sample variable to export, e.g.:

```py
# SPDX-License-Identifier: Apache-2.0
FOO='bar'
```

4. Attempt to import this from any other module, let's say `src/instructlab/model/model.py`:
```py
# somewhere in the file:
from .mytest import FOO
```


6. Run `pip install .`
7. Try to run `ilab --version`

And then to see that the import works correctly, you can do:

1. `pip install -e .`
2. `ilab --version`

**Comment by nathan-weinberg** [comment]
@tiran do you have any ideas as to how we might be able to resolve this?

**Comment by tiran** [comment]
The behavior is caused by setuptools-scm. It generates the file list from VCS. Call my Captain Obvious, the easiest way to work around the problem is to add the file to git. `git add`, `git commit` and you are good.

If you want an editable installation, then you can do `pip install --no-deps -e .`. Tox has also a `tox devenv` command. Or you can temporary set `package = editable` in `tox.ini`.

DO NOT commit the change. Our CI has to test the proper installation method. Editable installations behave different than wheel installations.

**Comment by RobotSail** [comment]
@tiran Could we just disable that feature? This type of thing seems like it would be best caught by CI.
