### ISSUE TITLE
`ilab model download` stores models in roaming `~/.local/share`

### ISSUE THREAD

**Issue by tiran** [instructlab/instructlab#1705]
**Describe the bug**
PR #1471 changed the location of model download path. They are now stored in `XDG_DATA_HOME` (`~/.local/share`). The directory is designed for roaming, persistent data. On my systems, the directory is synchronized between multiple machines and backed up remotely.

Downloaded models are by definition transient data that should live in `XDG_CACHE_HOME`. The Hugging Face libraries do it right and uses `~/.cache` for its download cache.

**To Reproduce**
`ilab model download`

**Expected behavior**
Downloaded models should be in `~/.cache`

**Comment by jaideepr97** [comment]
@tiran do you think this needs to be in 0.18, or can this be moved to 0.19?

**Comment by tiran** [comment]
I included the ticket in 0.18 milestone because I believe we need to address this before the code is used in production. Other paths need to be verified, too.

**Comment by n1hility** [comment]
@tiran hmm I'm uncertain on this one. The spec seems unclear but tends to imply everything is local to the system, and there are other cases of large payloads in these directories. For example, Container storage is stored in XDG_DATA_HOME (.local/share/containers/storage). I can see the argument that downloaded models are temporary and belong in XDG_CACHE_HOME, but models that are trained would need to be in XDG_DATA_HOME, since that is the defined location for state that is retained. It sounds like these would also create the same problem for your use case.

It like a flaw in the spec in that they should have clearly differentiated remote/roaming vs pure local.

**Comment by tiran** [comment]
I agree. The [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) is a bit vague. It is lacking guidelines in regards of roaming/local and backup/non-backup locations. Windows' user directory spec does a better job. It helps to think about the problem as "how does the directory map to [Filesystem Hierarchy Standard](https://www.pathname.com/fhs/)" and "how is the directory mapped on Windows?". Debian's docs on XDG has a useful table with suggestions roaming, backup, and size.

- https://docs.fedoraproject.org/en-US/packaging-guidelines/#_filesystem_layout
- https://wiki.debian.org/XDGBaseDirectorySpecification
- https://wiki.gentoo.org/wiki/XDG/Base_Directories

I guess, Podman and crun use `.local/share/containers/storage`, because they cannot use a different tree for downloaded layers and locally created layers. In a perfect world, they would use `~/.cache` for pulled layers from a registry and `~/.local/share` for locally created layers`.

In the end, it's all about finding the right balance and what's best for our users. The decision boils down to importance, size, and speed. (System cache directories are typically very fast NV storages or even tempfs.)

- default to `XDG_CACHE_HOME` for everything
- if it's ephemeral data or anything that can be fetched or reconstructed easily, definitely go for `XDG_CACHE_HOME`
- if it's a config file, use `XDG_CONFIG_HOME`
- if it's transient data like unimportant log file, history file, or small state file, then use `XDG_STATE_HOME`
- if it's a Unix socket or small ephemeral file, use `XDG_RUNTIME_DIR`
- if data is important and cannot be reconstructed easily (or at all), then use `XDG_DATA_HOME`

IMO other files and directories should be moved from user's data directory to user's cache directory. Is there any reason we need to persist and back up internal data (`INTERNAL_DIR`)? Wouldn't it be more appropriate to have some of this data on fast and volatile storage? Other data like eval and SDG output should probably be persistent and kept between runs for auditing and diagnostic purposes.

**Comment by RobotSail** [comment]
@mbestavros

**Comment by russellb** [comment]
FWIW, my instinct is that these are more data than cache. We're putting this path in our config files. It's not something someone can clear at any time without breaking their config. That's what pushes me toward data. It's not something handled gracefully if it got wiped.

I'm not going to block this, though.

**Comment by mbestavros** [comment]
I've been thinking about this some while working on #1762.

In my mind, there are really _three_ types of model files:

1) Downloaded models
2) Intermediate checkpoints
3) Finished, trained models

There's some disagreement about the appropriate place to put 1), but I suspect we'll all generally agree that 2) should be stored ephemerally (i.e. in cache), and 3) should be stored persistently in user data (since it's a finished model).

I know 2) and 3) run out of the scope of this immediate issue, so I'll open a follow up to cover them. Relevant since my PR (https://github.com/instructlab/instructlab/pull/1762) begins to touch all of them.
