### ISSUE TITLE
Add additional GPUs flag to ilab model serve

### ISSUE THREAD

**Issue by alinaryan** [instructlab/instructlab#1904]
An extra `-- --tensor-parallel-size n` (n being the num of gpus) is needed in the `ilab model serve` command when serving the model. This should be doc'ed in the readme. Also, we would like to point out that everything after that flag is expected to be a vLLM command. 

In 0.19.0, the vLLM args should become flags for `ilab model serve`.

**Comment by mairin** [comment]
What is the outcome if this doesn't make it to 0.18.0? Trying to understand whether or not this is a true blocker.

**Comment by alimaredia** [comment]
@mairin This issue is actually 2 things.
1. This is a UX improvment. It's to give the user the option to specify `--gpus` for `ilab model serve`. Right now to specify that they'd need to edit the config file, and change the `vllm_args` section to include a specific vLLM flag. 

Charlie opened up https://github.com/instructlab/instructlab/pull/1931 to fix that issue. I narrowed down the scope for his PR in https://github.com/instructlab/instructlab/pull/1974. I think we can get 1974 in today. 

I think providing just the flag for ilab serve should be a blocker. What Charlie had done by a gpu value into the serving config has bigger scope and I think we could move to the next release.
 
2. Upstream Docs for item 1.

CC: @alinaryan @cdoern
