### ISSUE TITLE
evaluate: when a spawned vLLM process dies, the controlling process should detect, report, and exit

### ISSUE THREAD

**Issue by RobotSail** [instructlab/instructlab#1965]
**Describe the bug**

When you're spawning a vLLM without a separate process, then whatever spawned it should be able to detect "hey we died here" rather than sending it into a retry loop. Since we have to wait until the retry loop fails before it reports the failure.

This shouldn't require that `--enable-serving-output` was passed in order to know that in the case of `ilab model evaluate`.

**To Reproduce**

1. Serve a large model without enough resources

**Expected behavior**

If evaluate serving fails, we should detect that failure and exit early rather than retrying 80 times until failure.

**Comment by nathan-weinberg** [comment]
@danmcp I feel like we had a reason for the 80 retries originally but I can't remember what it was, do you?

**Comment by danmcp** [comment]
I just happened to fix this a couple days ago:  https://github.com/instructlab/instructlab/pull/1969

> @danmcp I feel like we had a reason for the 80 retries originally but I can't remember what it was, do you?

The 80 attempts (which is now 300 and configurable - https://github.com/instructlab/instructlab/pull/1968) does still need to be in place because it can take up to 10ish mins to start with some models.  But it no longer sits there waiting if the vllm process is dead.
