### ISSUE TITLE
`ilab model test` doesn't do anything

### ISSUE THREAD

**Issue by jjasghar** [instructlab/instructlab#2147]
https://github.com/instructlab/instructlab/blob/a21129abc8badf4b3a699273e503fa9e9745e664/README.md?plain=1#L699

Walking through the steps on my M3 Mac, attempting to run `ilab model test` this happens:

```bash
Epoch 1: Iter 100: Val loss 0.967, Val took 33.072s
Iter 100: Saved adapter weights to /Users/jjasghar/Library/Application Support/instructlab/checkpoints/instructlab-granite-7b-lab-mlx-q/adapters-100.npz.
(venv-instructlab-0.18-3.11) ➜  instructlab ilab model test
NOTE: Adapter file does not exist. Testing behavior before training only. - /Users/jjasghar/Library/Application Support/instructlab/checkpoints/adapters.npz
'/Users/jjasghar/Library/Application Support/instructlab/internal/test.jsonl' not such file or directory. Did you run 'ilab model train'?
(venv-instructlab-0.18-3.11) ➜  instructlab
```

I ran `ilab model train` but it seems it can't find the `test.jsonl`?

**Comment by bjhargrave** [comment]
I think this is a dup of #2110.

**Comment by nathan-weinberg** [comment]
@jjasghar can you confirm if that's the case?

**Comment by jaideepr97** [comment]
IMO we should probably deprecate `ilab model test`

It is very mac specific. The original workflow was that `ilab model train` on mac produces an adapter file. `ilab model test` is used as a smoke test by essentially performing inference on just that adapter file. Then `ilab model convert` fuses that adapter file into the base model before converting it to `gguf` format

I recently proposed https://github.com/instructlab/instructlab/issues/2351 which re-designs `ilab model convert` to be more generic and useable to everyone. If we go that route, we would be removing the fusing logic from `ilab model convert` 
This would essentially render `ilab model test` useless because we would need a way to auto-fuse an adapter into the base model before conversion. (Unless we really value the ability to smoke test and manually fuse adapters, in which case would need to introduce a separate `ilab model fuse` or something)

Going the auto-fuse route would align the workflow with linux as well. In the future we can try and extend some kind of evaluation mechanism to pick the best adapter for training (which will replace the manual eval we do via `ilab model test` today)

thoughts @jjasghar @bjhargrave @nathan-weinberg ?

**Comment by bjhargrave** [comment]
> align the workflow with linux as well

I am all for aligning the workflow across macOS and linux. This further shows the need for regular e2e testing on macOS in addition to linux.

**Comment by jaideepr97** [comment]
would we be okay with closing this issue in favor of #2373 ?
