### ISSUE TITLE
[Phase 1 Profiles] HW auto-detect for CLI profiles

### ISSUE THREAD

**Issue by ktam3** [instructlab/instructlab#2155]
It would be nice to implement a way to auto-detect hardware, and suggest an appropriate default config profile for each of the components based on the hardware we detect. This will make for a smoother user experience that requires less work on the user's part to maximize the usage of their hardware and optimize performance (and get better output results.)

 
Feature Overview (aka. Goal Summary)
As a user, I want RHEL AI to detect the hardware I am working with so I do not have to choose/edit config files. 

Goals (aka. expected user outcomes)
This will make getting started with the process easier. Users will not have to look for relevant config files and reduces scope for errors.

Questions to Answer:
1. Will this be applicable for all hardware configurations (eg. RHEL AI suitable ones - 4xH100s and so on, as well as others, eg. 4xA10s)?
2. Will all the different components (eval, training, generate) be updated? 

Issues in this Epic:
- [ ] #2159

**Comment by ktam3** [comment]
Related to Epic #2108

**Comment by TomasTomecek** [comment]
Came here to open this issue, glad to see it's already reported.

Running `config init` with ilab 1.18, it's frustrating to me to see the different profiles offered for multiple GPUs while sitting only on a single T4 GPU. Since the configuration is pretty complex, it's a big task right from the beginning to update the configuration file for someone new to InstructLab.

It would be much more helpful if ilab already detected my GPUs (especially for a single card) and adapted the config automatically. This especially applies to `serve` and `generate`, I understand that training is more complex.
