### ISSUE TITLE
Some H100/A100 systems are not correctly identified by auto detection

### ISSUE THREAD

**Issue by ktam3** [instructlab/instructlab#2706]
The H100 profiles do not match the expected code to file name translation logic since this card reports as:

_CudaDeviceProperties(name=‘NVIDIA H100 80GB HBM3’, major=9, minor=0, total_memory=80994MB, multi_processor_count=132)

There are several H100 variants:

0x2321, 0x1839, 0x10de, "NVIDIA H100 NVL"
0x2330, 0x16c0, 0x10de, "NVIDIA H100 80GB HBM3"
0x2330, 0x16c1, 0x10de, "NVIDIA H100 80GB HBM3"
0x2331, 0x1626, 0x10de, "NVIDIA H100 PCIe"
0x2339, 0x17fc, 0x10de, "NVIDIA H100"

A full list of all Nvidia card identifiers can be obtained in the open drivers (scroll past the nulls):
https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/src/nvidia/generated/g_nv_name_released.h

**Comment by nathan-weinberg** [comment]
We are also seeing this issue affect A100 cards

**Comment by cdoern** [comment]
Hey, I think a long term solution to this is to introduce metadata to the config: https://github.com/instructlab/instructlab/pull/2713

Rather than reading file names, as we scale and want a config to apply to a specific GPU or a config to apply other a set of GPUs, we will need more granular control over the profile system. I think #2173 (I will add this to the profile system in that PR), is the right path forward

**Comment by jaideepr97** [comment]
> Hey, I think a long term solution to this is to introduce metadata to the config: #2713
> 
> Rather than reading file names, as we scale and want a config to apply to a specific GPU or a config to apply other a set of GPUs, we will need more granular control over the profile system. I think #2173 (I will add this to the profile system in that PR), is the right path forward

I agree that generally moving away from filename based operations is a good thing 
though im not sure I see how that alone will address the issue of not matching the card name perfectly. We will still need some heuristic to properly categorize the card name, we will now just be checking against a field inside the file rather than the name of the file

**Comment by cdoern** [comment]
@jaideepr97 , this heuristic will allow us to store specific types of GPU information in the config. 

The PR isn't ready yet, but the SKU field will end up probably being a list like [PCIe, ...] Where if the gpu matches any of the sku information, and the count and type match as well then we can apply the config to the system. 

This allows us to apply configs as specifically or as broadly as we want.

**Comment by cdoern** [comment]
The application and matching system will also be much much easier and sustainable

**Comment by nathan-weinberg** [comment]
Related to https://github.com/instructlab/instructlab/issues/2489
