### ISSUE TITLE
PyPi full release tracker

### ISSUE THREAD

**Issue by cdoern** [instructlab/instructlab#972]
this issue is a tracker for the 5/30 release in which we intend to release the package publicly on PyPi. Before this milestone, everything should be done as beta, a test, or however PyPi distinguishes between fully published packages and tests.

relates to #256

**Comment by tiran** [comment]
Pre-releases are defined in [PEP-440](https://peps.python.org/pep-0440/#pre-releases). Any release with `a` (alpha`), `b` (beta), or `rc` (release candidate) in the public version number is considered a pre-release. There are also `dev` releases, but they should not get uploaded to production PyPI https://.pypi.org/ . `pip` ignores pre-releases by default. Users can install a pre-release with `pip install --pre NAME`.

There is also a test instance of PyPI: https://test.pypi.org/ . It is an independent instance of PyPI with its own user and package database. Test PyPI can be used to upload dev releases.

These days the recommend workflow for PyPI releases uses `setuptools-scm` to generate versions from git tags, sigstore for signing, `pypa/gh-action-pypi-publish` for uploading and [trusted publisher](https://docs.pypi.org/trusted-publishers/) for authentication:

* `git tag v0.14.0 ...`
* `git push upstream refs/tags/v0.14.0`
* create a new release from the tag on GitHub
* publish the release
* the `publish` event triggers `.github/workflows/pypi.yaml` and runs build-package + publish-pypi jobs
* the build-package job creates sdist and whl artifacts based on the tag name
* the publish-pypi job signs the packages and uses trusted publishing to upload the artifacts to PyPI. Internally it uses short-lived OIDC tokens

Test releases to Test PyPI are a bit simpler

* a merge to `main` branch triggers `.github/workflows/pypi.yaml` build-package + publish-test-pypi job
* the build-package job creates sdist and whl artifacts based on the last tag + count of commits since tag + git commit hash
* the publish-test-pypi job uses trusted publishing to upload the artifacts to Test PyPI

Nit pick: `s/PyPi/PyPI/g` :) "Pie Pee Eye" is the Python Package Index. "Pie Pie" is the Python implementation PyPy (Python implemented in Python).

**Comment by tiran** [comment]
I was asked how package build process works. It's complicated and depends on the project configuration. The short version:

## build-package
- [hynek/build-and-inspect-python-package](https://github.com/hynek/build-and-inspect-python-package) uses [build](https://pypi.org/project/build/) frontend and [twine](https://pypi.org/project/twine) + [check-wheel-contents](https://pypi.org/project/check-wheel-contents) to validate artifacts.
- `build` uses information from our `pyproject.toml` to create a build environment and run the build backend. In our case, the backend is `setuptools.build_meta`
- the backend creates a source distribution (sdist tar ball) and wheel. `setuptools.build_meta` also uses `pyproject.toml` for project information and `setuptools` tool configuration.
- twine and check-wheel-contents perform various checks
- finally artifacts are uploaded to GA with `actions/upload-artifact`

## publish
- artifacts from previous step are downloaded with `actions/download-artifact`
- [pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish) uses [twine](https://pypi.org/project/twine) to upload packages. The process is authenticated with short-lived OIDC tokens and PyPI's trusted publisher feature.

**Comment by nathan-weinberg** [comment]
@tiran Is there anything else that needs to be done for this before 5/30? @cdoern is thinking that once we have our first PyPi release with `0.15.1` it could maybe be closed out

**Comment by tiran** [comment]
@nathan-weinberg Yes, I agree. Let's wait and see if 0.15.1 deploys to PyPI, then close this issue.

**Comment by tiran** [comment]
Yeah, sdist and wheel files are there and GH release has the signatures, too.

- https://pypi.org/project/instructlab/0.15.1/#files 
- https://github.com/instructlab/instructlab/actions/runs/9213059585
- https://github.com/instructlab/instructlab/releases/tag/v0.15.1
